/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.poly.pro_1041.it17322.group4.view;

import com.poly.pro_1041.it17322.group4.domainmodel.Account;
import com.poly.pro_1041.it17322.group4.domainmodel.ChiTietSanPham;
import com.poly.pro_1041.it17322.group4.domainmodel.KhuyenMai;
import com.poly.pro_1041.it17322.group4.domainmodel.Loai;
import com.poly.pro_1041.it17322.group4.domainmodel.LoaiKM;
import com.poly.pro_1041.it17322.group4.domainmodel.TrangThaiKM;
import com.poly.pro_1041.it17322.group4.domainmodel.XDate;
import com.poly.pro_1041.it17322.group4.repository.LoaiKMRepository;
import com.poly.pro_1041.it17322.group4.response.ViewCTSPResponse;
import com.poly.pro_1041.it17322.group4.response.ViewKhuyenMaiResponse;
import com.poly.pro_1041.it17322.group4.response.ViewLoaiKMResponse;
import com.poly.pro_1041.it17322.group4.response.ViewTrangThaiKMResponse;
import com.poly.pro_1041.it17322.group4.service.ViewHoaDonService;
import com.poly.pro_1041.it17322.group4.service.ViewKhuyenMaiService;
import com.poly.pro_1041.it17322.group4.service.ViewLoaiService;
import com.poly.pro_1041.it17322.group4.service.impl.ViewHoaDonServiceImpl;
import com.poly.pro_1041.it17322.group4.service.impl.ViewKhuyenMaiServiceImpl;
import com.poly.pro_1041.it17322.group4.service.impl.ViewLoaiServiceImpl;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Lenovo
 */
public class ViewKhuyenMai extends javax.swing.JPanel {

    /**
     * Creates new form ViewKhuyenMai
     */
    private ViewHoaDonService vhds = new ViewHoaDonServiceImpl();
    private ViewKhuyenMaiService vkms = new ViewKhuyenMaiServiceImpl();
    private ViewLoaiService vls = new ViewLoaiServiceImpl();
    private DefaultTableModel tbsp = new DefaultTableModel();
    private DefaultTableModel tbkm = new DefaultTableModel();
    private DefaultComboBoxModel dcbmLoaiSP = new DefaultComboBoxModel();
    private DefaultComboBoxModel dcbmLoaiKM = new DefaultComboBoxModel();
    private List<ViewKhuyenMaiResponse> listVKM = new ArrayList<>();
    private List<ViewLoaiKMResponse> listVLKM = new ArrayList<>();
    private List<ViewTrangThaiKMResponse> listVTTKM = new ArrayList<>();
    private List<ViewCTSPResponse> listSanPham = new ArrayList<>();
    private List<Loai> listLoaiSP = new ArrayList<>();
    private LoaiKMRepository lkmrp = new LoaiKMRepository();
    int index;

    public ViewKhuyenMai(Account a) {
        initComponents();

//        tbSanPham.setModel(tbsp);
        tbsp = (DefaultTableModel) tbSanPham.getModel();
        tbKhuyenMai.setModel(tbkm);

        String[] headerSanPham = {"Tên SP", "Mã SP", "Giá", "Tên KM", "Chọn"};
        String[] headerKhuyenMai = {"Tên KM", "Ngày bắt đầu", "Ngày kết thúc", "% Khuyến mãi", "Loại khuyến mãi", "Trạng thái"};
        tbsp.setColumnIdentifiers(headerSanPham);
        tbkm.setColumnIdentifiers(headerKhuyenMai);

        listVKM = vkms.getAllKM();
        listVLKM = vkms.getAllLKM();
        listVTTKM = vkms.getAllTTKM();
        listSanPham = vhds.getAllSP();
        listLoaiSP = vls.getAll();

        showDataTableKhuyenMai(listVKM);
        showDataTableSanPham(listSanPham);

        for (Loai loaiSP : listLoaiSP) {
            dcbmLoaiSP.addElement(loaiSP.getTen());
        }
        for (ViewLoaiKMResponse viewLoaiKMResponse : listVLKM) {
            dcbmLoaiKM.addElement(viewLoaiKMResponse.getTen());
        }
        rdoNgungHoatDong.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbKhuyenMai = new javax.swing.JTable();
        txtSearch = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbSanPham = new javax.swing.JTable();
        btnApDung = new javax.swing.JButton();
        txtSearchSP = new javax.swing.JTextField();
        btnChonHet = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jComboBox6 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtGiamGia = new javax.swing.JTextField();
        txtTenCT = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        rdoHoatDong = new javax.swing.JRadioButton();
        rdoNgungHoatDong = new javax.swing.JRadioButton();
        btnLuu = new javax.swing.JButton();
        btnCapNhat = new javax.swing.JButton();
        btnDoi = new javax.swing.JButton();
        btnMoi = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        cbbLoaiKM = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        txtMaKM = new javax.swing.JTextField();
        txtBatDau = new com.toedter.calendar.JDateChooser();
        txtKetThuc = new com.toedter.calendar.JDateChooser();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "Danh sách khuyến mãi", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N
        jPanel5.setPreferredSize(new java.awt.Dimension(759, 158));

        tbKhuyenMai.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbKhuyenMai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbKhuyenMaiMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbKhuyenMai);

        txtSearch.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtSearchCaretUpdate(evt);
            }
        });
        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 624, Short.MAX_VALUE))
                .addGap(20, 20, 20))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "Danh sách sản phẩm", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N
        jPanel6.setPreferredSize(new java.awt.Dimension(759, 158));

        tbSanPham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Tên SP", "Loại SP", "Còn tồn", "Chọn", "Title 5"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbSanPham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbSanPhamMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tbSanPham);

        btnApDung.setText("Áp dụng");
        btnApDung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApDungActionPerformed(evt);
            }
        });

        txtSearchSP.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtSearchSPCaretUpdate(evt);
            }
        });

        btnChonHet.setText("Chọn hết");
        btnChonHet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChonHetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 624, Short.MAX_VALUE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtSearchSP, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(btnChonHet, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(btnApDung, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(20, 20, 20))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(txtSearchSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnApDung)
                    .addComponent(btnChonHet))
                .addContainerGap())
        );

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "Thông tin khuyến mãi", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N
        jPanel7.setPreferredSize(new java.awt.Dimension(759, 158));

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel6.setText("Hình thức giảm giá");

        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel1.setText("Tên chương trình");

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel2.setText("Mức giảm giá");

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel5.setText("TG bắt đầu");

        jLabel7.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel7.setText("TG kết thúc");

        jLabel8.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel8.setText("Trạng thái");

        buttonGroup1.add(rdoHoatDong);
        rdoHoatDong.setText("Đang hoạt động");

        buttonGroup1.add(rdoNgungHoatDong);
        rdoNgungHoatDong.setSelected(true);
        rdoNgungHoatDong.setText("Ngừng hoạt dộng");

        btnLuu.setBackground(new java.awt.Color(0, 102, 102));
        btnLuu.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnLuu.setText("Lưu");
        btnLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuActionPerformed(evt);
            }
        });

        btnCapNhat.setBackground(new java.awt.Color(0, 102, 102));
        btnCapNhat.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnCapNhat.setText("Cập nhật");
        btnCapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatActionPerformed(evt);
            }
        });

        btnDoi.setBackground(new java.awt.Color(0, 102, 102));
        btnDoi.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnDoi.setText("Hủy KM");
        btnDoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoiActionPerformed(evt);
            }
        });

        btnMoi.setBackground(new java.awt.Color(0, 102, 102));
        btnMoi.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnMoi.setText("Tạo mới");
        btnMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoiActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel9.setText("Loại KM");

        cbbLoaiKM.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Theo %", "Theo số tiền" }));

        jLabel10.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel10.setText("Mã KM");

        txtBatDau.setDateFormatString("dd-MM-yyyy");

        txtKetThuc.setDateFormatString("dd-MM-yyyy");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnLuu, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnMoi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel7Layout.createSequentialGroup()
                                        .addComponent(rdoHoatDong)
                                        .addGap(18, 18, 18)
                                        .addComponent(rdoNgungHoatDong))
                                    .addGroup(jPanel7Layout.createSequentialGroup()
                                        .addComponent(btnCapNhat, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnDoi, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtMaKM, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel7Layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtTenCT, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel7Layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addGap(80, 80, 80)
                                        .addComponent(cbbLoaiKM, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel7Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtKetThuc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtBatDau, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtGiamGia, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE))))))
                        .addGap(282, 282, 282)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox6, 0, 1, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtTenCT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(cbbLoaiKM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtGiamGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(txtBatDau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(txtKetThuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(txtMaKM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(jLabel8)
                .addGap(31, 31, 31)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdoHoatDong)
                    .addComponent(rdoNgungHoatDong))
                .addGap(37, 37, 37)
                .addComponent(btnLuu, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCapNhat, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDoi, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(81, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 662, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 662, Short.MAX_VALUE))
                .addGap(30, 30, 30)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 661, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tbKhuyenMaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbKhuyenMaiMouseClicked
        index = tbKhuyenMai.getSelectedRow();
        if (index == -1) {
            return;
        }
        txtMaKM.setText(listVKM.get(index).getMa().toString());
        txtTenCT.setText(tbKhuyenMai.getValueAt(index, 0).toString());
        txtGiamGia.setText(tbKhuyenMai.getValueAt(index, 3).toString());
        txtBatDau.setDate(XDate.toDate(tbKhuyenMai.getValueAt(index, 1).toString()));
        txtKetThuc.setDate(XDate.toDate(tbKhuyenMai.getValueAt(index, 2).toString()));

        if (tbKhuyenMai.getValueAt(index, 4).toString().equalsIgnoreCase("%")) {
            cbbLoaiKM.setSelectedIndex(0);

        } else {
            cbbLoaiKM.setSelectedIndex(1);
        }
        if (listVKM.get(index).getTrangThaiKM().getId() == 1) {
            rdoHoatDong.setSelected(true);
        } else {
            rdoNgungHoatDong.setSelected(true);
        }

    }//GEN-LAST:event_tbKhuyenMaiMouseClicked

    public void fillIndex() {
        index = tbKhuyenMai.getSelectedRow();
        if (index == -1) {
            return;
        }
        txtMaKM.setText(listVKM.get(index).getMa().toString());
        txtTenCT.setText(tbKhuyenMai.getValueAt(index, 1).toString());
        txtGiamGia.setText(tbKhuyenMai.getValueAt(index, 4).toString());
        txtBatDau.setDate(XDate.toDate(tbKhuyenMai.getValueAt(index, 2).toString()));
        txtKetThuc.setDate(XDate.toDate(tbKhuyenMai.getValueAt(index, 3).toString()));

        if (tbKhuyenMai.getValueAt(index, 5).toString().equalsIgnoreCase("%")) {
            cbbLoaiKM.setSelectedIndex(0);

        } else {
            cbbLoaiKM.setSelectedIndex(1);
        }
        if (listVKM.get(index).getTrangThaiKM().getId() == 1) {
            rdoHoatDong.setSelected(true);
        } else {
            rdoNgungHoatDong.setSelected(true);
        }
        tbKhuyenMai.setRowSelectionInterval(index, index);
        tbKhuyenMai.setRowSelectionAllowed(true);
    }
    private void tbSanPhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbSanPhamMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tbSanPhamMouseClicked

    private void btnLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuActionPerformed

        if (checkForm() == null) {

            return;
        }
        index = listVKM.size() - 1;
        ViewKhuyenMaiResponse vkmr = checkForm();

        JOptionPane.showMessageDialog(this, vkms.addKhuyenMai(vkmr));
        listVKM = vkms.getAllKM();

        showDataTableKhuyenMai(listVKM);

        txtTenCT.setText(null);
        txtGiamGia.setText(null);
        txtBatDau.setDateFormatString(null);
        txtKetThuc.setDateFormatString(null);
        txtMaKM.setText(null);
        txtBatDau.setCalendar(null);
        txtKetThuc.setCalendar(null);
        fillIndex();
    }//GEN-LAST:event_btnLuuActionPerformed

    private void btnMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoiActionPerformed
        try {
            txtTenCT.setText(null);
            txtGiamGia.setText(null);
            txtBatDau.setDateFormatString(null);
            txtKetThuc.setDateFormatString(null);
            txtMaKM.setText(null);
            txtBatDau.setCalendar(null);
            txtKetThuc.setCalendar(null);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnMoiActionPerformed

    private void btnDoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoiActionPerformed
        try {
            if (tbKhuyenMai.getSelectedRow() == -1) {
                JOptionPane.showMessageDialog(this, "Chưa chọn KM để tắt");
                return;
            }

            int hoi = JOptionPane.showConfirmDialog(this, "Muốn tắt KM ?");
            if (hoi != JOptionPane.YES_OPTION) {
                return;
            }
            index = tbKhuyenMai.getSelectedRow();
            boolean check = true;
//            List<ChiTietSanPham> list = vkms.
            int ttkm = 2;
            ViewKhuyenMaiResponse vkmr = listVKM.get(index);
            TrangThaiKM trangThaiKM = new TrangThaiKM(ttkm, null, null);
            List<ViewCTSPResponse> list = vkms.getAllSPUpdateNgungKM(vkmr.getId());
            for (ViewCTSPResponse vctspr : list) {
                if (vkmr.getLoaiKM().getId() == 1) {
                    Double giaCu = Double.valueOf(String.valueOf(vctspr.getGia()));
                    Double giaMoi = (Double.valueOf(vkmr.getGiaKM()) * 100 / (100 - Double.valueOf(vkmr.getGiaKM())) + 100) * giaCu / 100;
                    vctspr.setGia(BigDecimal.valueOf(giaMoi));
                } else {
                    Double giaCu = Double.valueOf(String.valueOf(vctspr.getGia()));
                    vctspr.setGia(BigDecimal.valueOf(giaCu + Double.valueOf(vkmr.getGiaKM())));
                }
                vctspr.setKm(null);
                vkms.updateCTSPKM(vctspr);
            }
            vkmr = new ViewKhuyenMaiResponse(vkmr.getId(), trangThaiKM, vkmr.getLoaiKM(), vkmr.getMa(), vkmr.getTen(), vkmr.getNgayBatDau(), vkmr.getNgayKetThuc(), vkmr.getGiaKM());

            check = vkms.updateKhuyenMai(vkmr);

            listVKM = vkms.getAllKM();
            showDataTableKhuyenMai(listVKM);
            txtTenCT.setText(null);
            txtGiamGia.setText(null);
            txtBatDau.setDateFormatString(null);
            txtKetThuc.setDateFormatString(null);
            txtMaKM.setText(null);
            txtBatDau.setCalendar(null);
            txtKetThuc.setCalendar(null);
            JOptionPane.showMessageDialog(this, "Tắt KM thành công");
            listSanPham = vkms.getAllSP();
            showDataTableSanPham(list);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnDoiActionPerformed

    private void btnCapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatActionPerformed
        index = tbKhuyenMai.getSelectedRow();
        int hoi = JOptionPane.showConfirmDialog(this, "Muốn cập nhật KM ?");
        if (hoi != JOptionPane.YES_OPTION) {
            return;
        }
        boolean check = true;
        ViewKhuyenMaiResponse vkmr = listVKM.get(index);

        int ttkm;
        if (rdoHoatDong.isSelected()) {
            ttkm = 1;
        } else {
            ttkm = 2;
        }
        int lkm;
        if (cbbLoaiKM.getSelectedIndex() == 0) {
            lkm = 1;
        } else {
            lkm = 2;
        }
        TrangThaiKM trangThaiKM = new TrangThaiKM(ttkm, null, null);
        LoaiKM loaiKM = new LoaiKM(lkm, null, null);

        vkmr = new ViewKhuyenMaiResponse(vkmr.getId(), trangThaiKM, loaiKM, txtMaKM.getText(), txtTenCT.getText(), txtBatDau.getDate(), txtKetThuc.getDate(), Float.valueOf(txtGiamGia.getText()));

        check = vkms.updateKhuyenMai(vkmr);

        listVKM = vkms.getAllKM();
        showDataTableKhuyenMai(listVKM);
        txtTenCT.setText(null);
        txtGiamGia.setText(null);
        txtBatDau.setDateFormatString(null);
        txtKetThuc.setDateFormatString(null);
        txtMaKM.setText(null);
        txtBatDau.setCalendar(null);
        txtKetThuc.setCalendar(null);
        JOptionPane.showMessageDialog(this, "Update thành công");
    }//GEN-LAST:event_btnCapNhatActionPerformed

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed

    }//GEN-LAST:event_txtSearchActionPerformed

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased

    }//GEN-LAST:event_txtSearchKeyReleased

    private void txtSearchCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtSearchCaretUpdate
        showDataTableKhuyenMai(vkms.Search(txtSearch.getText()));
    }//GEN-LAST:event_txtSearchCaretUpdate

    private void btnApDungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApDungActionPerformed

        int hoi = JOptionPane.showConfirmDialog(this, "Muốn áp dụng KM cho SP này ?");
        if (hoi != JOptionPane.YES_OPTION) {
            return;
        }

        if (checkThemKM() == false) {
            JOptionPane.showMessageDialog(this, "KM đã ngừng hoạt động");
            return;
        }

        for (int i = 0; i < listSanPham.size(); i++) {
            if (tbSanPham.getValueAt(i, 4).toString() == "true") {
                ViewCTSPResponse vctspr = listSanPham.get(i);
                boolean check = true;

                ViewKhuyenMaiResponse vkmr = listVKM.get(index);

                KhuyenMai km = new KhuyenMai();
                km.setId(vkmr.getId());
                Double giaMoi;
                if (cbbLoaiKM.getSelectedIndex() == 0) {
                    giaMoi = Double.parseDouble(String.valueOf(vctspr.getGia())) * (100 - vkmr.getGiaKM()) / 100;
                } else {
                    giaMoi = Double.parseDouble(String.valueOf(vctspr.getGia())) - vkmr.getGiaKM();
                }
                if (giaMoi < 0) {
                    JOptionPane.showMessageDialog(this, "Giá KM lớn hơn giá SP");
                    return;
                }
                vctspr.setKm(km);
                vctspr.setGia(BigDecimal.valueOf(giaMoi));

                check = vkms.updateCTSPKM(vctspr);
            }
        }

        listSanPham = vhds.getAllSP();
        showDataTableSanPham(listSanPham);
        JOptionPane.showMessageDialog(this, "Đã thêm KM cho sản phẩm");


    }//GEN-LAST:event_btnApDungActionPerformed

    private void txtSearchSPCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtSearchSPCaretUpdate
        showDataTableSanPham(vkms.SearchSP(txtSearchSP.getText()));
    }//GEN-LAST:event_txtSearchSPCaretUpdate

    private void btnChonHetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChonHetActionPerformed
        for (int i = 0; i < tbSanPham.getRowCount(); i++) {
            tbSanPham.setValueAt(true, i, 4);
        }
    }//GEN-LAST:event_btnChonHetActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApDung;
    private javax.swing.JButton btnCapNhat;
    private javax.swing.JButton btnChonHet;
    private javax.swing.JButton btnDoi;
    private javax.swing.JButton btnLuu;
    private javax.swing.JButton btnMoi;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbbLoaiKM;
    private javax.swing.JComboBox<String> jComboBox6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JRadioButton rdoHoatDong;
    private javax.swing.JRadioButton rdoNgungHoatDong;
    private javax.swing.JTable tbKhuyenMai;
    private javax.swing.JTable tbSanPham;
    private com.toedter.calendar.JDateChooser txtBatDau;
    private javax.swing.JTextField txtGiamGia;
    private com.toedter.calendar.JDateChooser txtKetThuc;
    private javax.swing.JTextField txtMaKM;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtSearchSP;
    private javax.swing.JTextField txtTenCT;
    // End of variables declaration//GEN-END:variables

    private void showDataTableKhuyenMai(List<ViewKhuyenMaiResponse> list) {
        tbkm.setRowCount(0);
//        int i = 1;
        for (ViewKhuyenMaiResponse x : list) {

            tbkm.addRow(new Object[]{x.getTen(), x.getNgayBatDau(), x.getNgayKetThuc(), x.getGiaKM(), x.getLoaiKM().getTen(), x.getTrangThaiKM().getTen()});

//            i++;
        }
    }

    private boolean checkThemKM() {
        int index3 = tbKhuyenMai.getSelectedRow();

        ViewKhuyenMaiResponse vkmr = listVKM.get(index3);
        if (vkmr.getTrangThaiKM().getId() == 2) {
            return false;
        }
        return true;
    }

    private void showDataTableSanPham(List<ViewCTSPResponse> list) {
        tbsp.setRowCount(0);

        for (ViewCTSPResponse view : list) {
//            tbsp.addRow(view.toDataRowKM());
            boolean chon = false;
            tbsp.addRow(new Object[]{view.getTen(), "SP" + view.getMa(), view.getGia(), view.getKm() == null ? "" : view.getKm().getTen(), chon});
        }
    }

    private ViewKhuyenMaiResponse checkForm() {
        String tenCT = txtTenCT.getText().trim();
//        Float giaKM = Float.valueOf(txtGiamGia.getText().trim());
        String giaKM = txtGiamGia.getText().trim();
        Date ngayBatDau = txtBatDau.getDate();
        Date ngayKetThuc = txtKetThuc.getDate();
        String maKM = txtMaKM.getText().trim();

        Calendar c1 = Calendar.getInstance();
        Calendar c2 = Calendar.getInstance();
        Calendar c3 = Calendar.getInstance();

        c1.setTime(txtBatDau.getDate());
        c2.setTime(txtKetThuc.getDate());
        c3.setTime(java.sql.Date.valueOf(LocalDate.now()));
        long a = (c1.getTime().getTime()) / (24 * 3600 * 1000);
        long b = (c2.getTime().getTime()) / (24 * 3600 * 1000);
        long c = (c3.getTime().getTime()) / (24 * 3600 * 1000);
        if (a < c) {
            JOptionPane.showMessageDialog(this, "Ngày bắt đầu phải lớn hơn hoặc bằng ngày hiện tại");
            return null;
        } else if (a > b) {
            JOptionPane.showMessageDialog(this, "Ngày bắt đầu phải nhỏ hơn ngày kết thúc");
            return null;
        }

        int lkm;
        if (cbbLoaiKM.getSelectedIndex() == 0) {
            lkm = 1;
        } else {
            lkm = 2;
        }
        int ttkm;
        if (rdoHoatDong.isSelected()) {
            ttkm = 1;
        } else {
            ttkm = 2;
        }
        TrangThaiKM trangThaiKM = new TrangThaiKM(ttkm, null, null);
        LoaiKM loaiKM = new LoaiKM(lkm, null, null);

        if (tenCT.isEmpty()
                || maKM.isEmpty()
                || giaKM.toString().isEmpty()
                || ngayBatDau.toString().isEmpty()
                || ngayKetThuc.toString().isEmpty()) {

            JOptionPane.showMessageDialog(this, "Không được để trống ô nhập");
            return null;
        }
        try {
            Float giamGia = Float.valueOf(giaKM);
            if (giamGia < 0) {
                JOptionPane.showMessageDialog(this, "Giá hoặc % phải lớn hơn 0");
                return null;
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Giá hoặc % phải là số ");
            return null;
        }

        Float giamGia = Float.valueOf(giaKM);

        return new ViewKhuyenMaiResponse(null, trangThaiKM, loaiKM, maKM, tenCT, ngayBatDau, ngayKetThuc, giamGia);
//        return null;
    }

//    private boolean checkNgay() {
//        Calendar c1 = Calendar.getInstance();
//        Calendar c2 = Calendar.getInstance();
//        Calendar c3 = Calendar.getInstance();
//        Date ngayBatDau1 = txtBatDau.getDate();
//        Date ngayKetThuc1 = txtKetThuc.getDate();
//        c1.setTime(ngayBatDau1);
//        c2.setTime(ngayKetThuc1);
//        c3.setTime(java.sql.Date.valueOf(LocalDate.now()));
//        long a = (c1.getTime().getTime()) / (24 * 3600 * 1000);
//        long b = (c2.getTime().getTime()) / (24 * 3600 * 1000);
//        long c = (c3.getTime().getTime()) / (24 * 3600 * 1000);
//        if (a < c) {
//            JOptionPane.showMessageDialog(this, "Ngày bắt đầu phải lớn hơn hoặc bằng ngày hiện tại");
//            return false;
//        } else if (a > b) {
//            JOptionPane.showMessageDialog(this, "Ngày bắt đầu phải nhỏ hơn ngày kết thúc");
//            return false;
//        } else {
//            return true;
//        }
//    }
}
